version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/account-api
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 777
    pattern: "**"
hooks:
  AfterInstall:
    - location: hooks/build.sh
      timeout: 1000
      runas: ec2-user
